
import numpy as np
from bs4 import BeautifulSoup
import requests
import pandas as pd


#programmableweb.com is the best search tool I've found. The problem is the searches are format dependent

def api_category(api_name):
    
    try:
    
        keyword = api_name.replace(" ", "%20")
        
        url = 'https://www.programmableweb.com/category/all/apis?keyword={}'.format(keyword)
        
        response = requests.get(url)
        content = BeautifulSoup(response.content, "html.parser")
        
        table = content.find('table', attrs={'class':'views-table cols-5 table'})
        dirty_categories = table.find_all('td', attrs={'class':'views-field views-field-field-article-primary-category'})
        
        clean_categories = []
        
        for i in np.arange(len(dirty_categories)):
            clean_category = dirty_categories[i].text
            clean_categories = np.append(clean_category, clean_categories)
            
        clean_categories_list = list(clean_categories)   
        #index is inverted for some reason
        clean_categories_list.reverse()
    
        return clean_categories_list[0]
        
    except AttributeError or IndexError:
        return 'error'
    


dictionary = open('<file path>')

with dictionary as f:
    mylist = list(f)
    
    
def clean_name(index):
    string = mylist[index].split(':')[0].replace("'", '').replace('{', '')
    if len(string) <=4:
        string = string
    elif (string[len(string)-1] =='I' and string[len(string)-2] == 'P' and string[len(string)-3] == 'A'):
        string = string[:-3]
    elif(string[len(string)-1] == 's' and string[len(string)-2] == 'I' and string[len(string)-3] == 'P' and string[len(string)-4] == 'A'):
        string = string[:-4]
        
    return string
        

categories = []

for i in np.arange(len(mylist)):
    api_name = clean_name(i)
    category = api_category(api_name)
    categories = np.append(categories, category)
    
names = []
for i in np.arange(len(mylist)):
    api_name = clean_name(i)
    names = np.append(names, api_name)
    
names = list(names)
categories = list(categories)
    

df = pd.DataFrame({'name':names, 'category': categories})
df = df[df.category != 'error']





categories = ['3D',
 'Accessibility',
 'Accounting',
 'Accounts',
 'Activity Streams',
 'Actors',
 'Addresses',
 'Adoption',
 'Adult',
 'Advertising',
 'Aes',
 'African',
 'Agents',
 'Aggregation',
 'Agile',
 'Agriculture',
 'Air Travel',
 'Alcohol',
 'Algorithms',
 'Analytics',
 'Animals',
 'Animation',
 'Annotations',
 'Announcements',
 'API',
 'API Description Languages',
 'API Design',
 'API Education',
 'API Management',
 'API Shutdowns',
 'API Strategy',
 'APIcon',
 'Application Development',
 'Applications',
 'Art',
 'Artificial Intelligence',
 'Asia',
 'Astrology',
 'Astronomy',
 'Atlas',
 'Attractions',
 'Auctions',
 'Audio',
 'Augmented Reality',
 'Australian',
 'Austrian',
 'Authentication',
 'Authorization',
 'Auto',
 'Automation',
 'Availability',
 'Avatars',
 'B2B',
 'B2D',
 'Babies',
 'Backend',
 'Backend-as-a-Service',
 'Background',
 'Backup',
 'Badges',
 'Banking',
 'Barcodes',
 'Bars',
 'Beauty',
 'Beer',
 'Belgian',
 'Best Practices',
 'Big Data',
 'Billing',
 'Bitcoin',
 'Blockchain',
 'Blogging',
 'Bluetooth',
 'Boating',
 'Booking',
 'Bookmarks',
 'Books',
 'Bots',
 'Brazilian',
 'Breweries',
 'Browsers',
 'Budget',
 'Business',
 'Caching',
 'Calendars',
 'Cameras',
 'Campaigns',
 'Canadian',
 'Captcha',
 'Catalogs',
 'Celebrities',
 'Charity',
 'Charts',
 'Chat',
 'Check-In',
 'Chemistry',
 'Chinese',
 'Cities',
 'Civics',
 'Classification',
 'Classifieds',
 'Climate',
 'Clothing',
 'Cloud',
 'Collaboration',
 'Collecting',
 'Colors',
 'Community',
 'Comparisons',
 'Competitions',
 'Compliance',
 'Contacts',
 'Content',
 'Content Delivery Network',
 'Content Management',
 'Contracts',
 'Conversions',
 'Copyright',
 'Coronavirus',
 'Countries',
 'Coupons',
 'COVID-19',
 'Credit Cards',
 'Crime',
 'Crowdsourcing',
 'Cryptocurrency',
 'Currency',
 'Customer Relationship Management',
 'Customer Service',
 'Customization',
 'Cycling',
 'Dashboards',
 'Data',
 'Data Mining',
 'Data-as-a-Service',
 'Database',
 'Database-as-a-Service',
 'Datacenter',
 'Dating',
 'DC-Area API Meetup',
 'Demographics',
 'Design',
 'Developer Relations',
 'Developers',
 'DevOps',
 'Diagrams',
 'Dictionary',
 'Dieting',
 'Digital Asset Management',
 'Directories',
 'Discounts',
 'DNA',
 'Documents',
 'Domains',
 'Drawing',
 'Drugs',
 'Earthquakes',
 'eBooks',
 'eCommerce',
 'Economics',
 'Editing',
 "Editor's Choice",
 'Education',
 'Electronic Signature',
 'Email',
 'Emergency',
 'Encoding',
 'Energy',
 'Engagement',
 'England',
 'Enterprise',
 'Entertainment',
 'Environment',
 'ERP',
 'eSports',
 'European',
 'Events',
 'Extraction',
 'Family',
 'Fantasy Sports',
 'Fashion',
 'Fax',
 'Feedback',
 'Feeds',
 'File Sharing',
 'Financial',
 'Fitness',
 'Flowers',
 'Fonts',
 'Food',
 'Forms',
 'Forums',
 'Framework',
 'French',
 'Funding',
 'Gadgets',
 'Gambling',
 'Games',
 'Genealogy',
 'Genetics',
 'Geography',
 'Geology',
 'German',
 'Gestures',
 'Gifts',
 'Goals',
 'Government',
 'Graphics',
 'GraphQL',
 'Greek',
 'Grocery',
 'Guatemalan',
 'Guides',
 'Hacking',
 'Haitian',
 'Hardware',
 'Health',
 'Healthcare',
 'History',
 'Hobbies',
 'Holidays',
 'Home Automation',
 'Hosting',
 'Hotels',
 'Housing',
 'HTML5',
 'Human Resources',
 'Humor',
 'IDE',
 'Identity',
 'Images',
 'Indian',
 'Infrastructure-as-a-Service',
 'Insurance',
 'Integration',
 'Intelligence',
 'International',
 'Internet of Things',
 'Inventory',
 'Invoicing',
 'iPaaS',
 'Israeli',
 'Italian',
 'Italy',
 'Japanese',
 'Jobs',
 'Keywords',
 'Korean',
 'Language',
 'Languages',
 'Law',
 'Learning Management Systems',
 'Library',
 'Licensing',
 'Linked Data',
 'Lists',
 'Localization',
 'Location',
 'Logistics',
 'Loyalty',
 'Lyrics',
 'Machine Learning',
 'Machine-to-Machine',
 'Magazines',
 'Mail',
 'Management',
 'Manufacturing',
 'Mapping',
 'Marine',
 'Marketing',
 'Marketplace',
 'Mashups',
 'Math',
 'Measurements',
 'Media',
 'Medical',
 'Medical Records',
 'Medicine',
 'Meetings',
 'Meme',
 'Merchants',
 'Messaging',
 'Metadata',
 'Mexican',
 'Microformat',
 'Microservices',
 'Migration',
 'Military',
 'Mobile',
 'Models',
 'Modules',
 'Monetization',
 'Monitoring',
 'Motion',
 'Mountains',
 'Movies',
 'Museums',
 'Music',
 'Names',
 'Natural Language Processing',
 'Nature',
 'Networking',
 'New York City',
 'News Services',
 'Newsletter',
 'Newsletters',
 'Non-Profit',
 'Nordic',
 'North America',
 'NoSQL',
 'Notes',
 'Notifications',
 'Nutrition',
 'OAuth',
 'OCR',
 'Office',
 'Open Banking',
 'Open Data',
 'Open Graph',
 'Open Source',
 'Optimization',
 'Ordering',
 'Organization',
 'Other',
 'Pakistani',
 'Panorama',
 'Parking',
 'Parsing',
 'Passports',
 'Passwords',
 'Pastebin',
 'Patents',
 'Payments',
 'PDF',
 'Performance',
 'Personal Information Management',
 'Pets',
 'Photos',
 'Planning',
 'Platform-as-a-Service',
 'Plugins',
 'Podcasts',
 'Police',
 'Politics',
 'Polls',
 'Postal',
 'Postcards',
 'Postcodes',
 'Predictions',
 'Presentations',
 'Prices',
 'Printing',
 'Privacy',
 'Products',
 'Profiles',
 'Project Management',
 'Protocol',
 'Prototype',
 'PSD2',
 'Publishing',
 'Purchasing',
 'Q&A',
 'QR Codes',
 'Quantified Self',
 'RAML',
 'Random',
 'Ratings',
 'RDF',
 'Real Estate',
 'Real Time',
 'Recognition',
 'Recommendations',
 'Recreation',
 'Reference',
 'Referrals',
 'Refunds',
 'Registration',
 'Registry',
 'Religion',
 'Rentals',
 'Reporting',
 'Reputation',
 'Reservations',
 'REST',
 'Restaurants',
 'Rewards',
 'Robots',
 'Romanian',
 'Russian',
 'Safety',
 'Sales',
 'Salesforce',
 'Satellites',
 'Scanning',
 'Scheduling',
 'Science',
 'Scottish',
 'Screenshots',
 'SDK',
 'Search',
 'Security',
 'Semantic Web',
 'Semantics',
 'Sentiment',
 'SEO',
 'Shipping',
 'Smartphone',
 'SOA',
 'Social',
 'Software-as-a-Service',
 'Solar',
 'Spam',
 'Spanish',
 'Spelling',
 'Sports',
 'Spreadsheets',
 'SQL',
 'Standards',
 'Statistics',
 'Stocks',
 'Storage',
 'Streaming',
 'Subscriptions',
 'Subtitles',
 'Summary',
 'Supernatural',
 'Supply Chain',
 'Support',
 'Surveys',
 'Sustainability',
 'Swagger (OpenAPI)',
 'Syncing',
 'Tagging',
 'Tasks',
 'Taxes',
 'Teleconferencing',
 'Telephony',
 'Testing',
 'Text',
 'Text-to-Speech',
 'Tickets',
 'Time',
 'Time Tracking',
 'Tools',
 'Top APIs',
 'Torrents',
 'Tourism',
 'Training',
 'Transactions',
 'Transcoding',
 'Transcription',
 'Translation',
 'Transparency',
 'Transportation',
 'Travel',
 'Trivia',
 'TV',
 'Tweets',
 'Typography',
 'Upload',
 'URL Shortener',
 'URLs',
 'USA',
 'Validation',
 'Verification',
 'Video',
 'Viewer',
 'Virtualization',
 'Visas',
 'Visualizations',
 'Voice',
 'VoIP',
 'Voting',
 'Water',
 'Weapons',
 'Wearable',
 'Weather',
 'Web Site Management',
 'Webcams',
 'Webhooks',
 'WebRTC',
 'Weddings',
 'Wholesale',
 'Wi-Fi',
 'Widgets',
 'Wiki',
 'Wine',
 'Wireless',
 'Word Processing',
 'Words',
 'Writing',
 'Zip Codes']
